### ISSUE TITLE
can't use --repot

### ISSUE THREAD

**Issue by strohi** [benschwarz/bonsai#18]
after having some trouble during install therubyracer and the tilt dependency issue got the stuff working, but now the --report function will not work.

```
 % bonsai -r
Copying page assets
/usr/lib64/ruby/gems/1.8/gems/bonsai-1.3.2/lib/bonsai/exporter.rb:115:in `generate_css': uninitialized constant Less::SyntaxError (NameError)
    from /usr/lib64/ruby/gems/1.8/gems/bonsai-1.3.2/lib/bonsai/exporter.rb:92:in `copy_public'
    from /usr/lib64/ruby/gems/1.8/gems/bonsai-1.3.2/lib/bonsai/exporter.rb:21:in `publish!'
    from /usr/lib64/ruby/gems/1.8/gems/bonsai-1.3.2/bin/bonsai:58
    from /usr/lib64/ruby/1.8/optparse.rb:1298:in `call'
    from /usr/lib64/ruby/1.8/optparse.rb:1298:in `parse_in_order'
    from /usr/lib64/ruby/1.8/optparse.rb:1254:in `catch'
    from /usr/lib64/ruby/1.8/optparse.rb:1254:in `parse_in_order'
    from /usr/lib64/ruby/1.8/optparse.rb:1248:in `order!'
    from /usr/lib64/ruby/1.8/optparse.rb:1339:in `permute!'
    from /usr/lib64/ruby/1.8/optparse.rb:1360:in `parse!'
    from /usr/lib64/ruby/gems/1.8/gems/bonsai-1.3.2/bin/bonsai:76
    from /usr/bin/bonsai:19:in `load'
    from /usr/bin/bonsai:19
```

**Comment by benschwarz** [comment]
It looks as though you need to `gem install less`, I'd recommend using a gem set until I release a new gem with simplified dependencies.

**Comment by benschwarz** [comment]
I'd try this again with the 1.4 version of the gem. If you're still interested.

**Comment by strohi** [comment]
i'd updates and tried a few minutes ago and its working. thx :)
