### ISSUE TITLE
Tilt dependency snafu on install

### ISSUE THREAD

**Issue by adrianocastro** [benschwarz/bonsai#19]
I tried installing bonsai using `sudo gem install bonsai` but it seems to be having some problems resolving its dependencies.

On first run it complained it was "_Unable to resolve dependencies: bonsai requires tilt (~> 0.9.0)_". So I manually installed tilt 0.9.0. After that I tried installing bonsai again and it said it was "_Unable to resolve dependencies: sinatra requires tilt (< 2.0, >= 1.2.2)_".

At this stage I removed tilt 0.9.0 and installed 1.3.3 but bonsai’s installation insisted I needed 0.9.0. In order for bonsai’s installation to go through I ended up having to have both versions of tilt installed but then bonsai can’t run because it’s "_Unable to activate sinatra-1.2.6, because tilt-0.9 conflicts with tilt (< 2.0, >= 1.2.2)_":

```$ bonsai --help
/usr/local/lib/ruby/site_ruby/1.8/rubygems/specification.rb:1615:in`raise_if_conflicts': Unable to activate sinatra-1.2.6, because tilt-0.9 conflicts with tilt (< 2.0, >= 1.2.2) (Gem::LoadError)
    from /usr/local/lib/ruby/site_ruby/1.8/rubygems/specification.rb:738:in `activate'
    from /usr/local/lib/ruby/site_ruby/1.8/rubygems/specification.rb:764:in`activate_dependencies'
    from /usr/local/lib/ruby/site_ruby/1.8/rubygems/specification.rb:758:in `each'
    from /usr/local/lib/ruby/site_ruby/1.8/rubygems/specification.rb:758:in`activate_dependencies'
    from /usr/local/lib/ruby/site_ruby/1.8/rubygems/specification.rb:742:in `activate'
    from /usr/local/lib/ruby/site_ruby/1.8/rubygems.rb:1211:in`gem'
    from /usr/local/bin/bonsai:18

``````

FYI:

```$ ruby --version
ruby 1.8.7 (2009-06-12 patchlevel 174) [i686-darwin10.8.0]
$ gem --version
1.8.10
``````

I apologise if this is an issue specific to my dev environment but I just can’t seem to find a way around it.

**Comment by adrianocastro** [comment]
Just realised that [this issue was reported about a year ago](https://github.com/benschwarz/bonsai/issues/17). Closing.
