### ISSUE TITLE
Compression error while using --repot

### ISSUE THREAD

**Issue by gburzynski** [benschwarz/bonsai#37]
```
bonsai -r

Copying page assets
Copying public files
Compressing javascript and stylesheets
/var/lib/gems/1.9.1/gems/yui-compressor-0.12.0/lib/yui/compressor.rb:96:in `rescue in block in compress': compression failed: No such file or directory - java -jar /var/lib/gems/1.9.1/gems/yui-compressor-0.12.0/lib/yui/../yuicompressor-2.4.8.jar --type css --charset utf-8 /tmp/yui_compress20151228-2842-1st3mu8 (YUI::Compressor::RuntimeError)
from /var/lib/gems/1.9.1/gems/yui-compressor-0.12.0/lib/yui/compressor.rb:99:in `block in compress'
from /var/lib/gems/1.9.1/gems/yui-compressor-0.12.0/lib/yui/compressor.rb:141:in `streamify'
from /var/lib/gems/1.9.1/gems/yui-compressor-0.12.0/lib/yui/compressor.rb:86:in `compress'
from /var/lib/gems/1.9.1/gems/bonsai-1.4.9/lib/bonsai/exporter.rb:50:in `block (2 levels) in compress_asset_path'
from /var/lib/gems/1.9.1/gems/bonsai-1.4.9/lib/bonsai/exporter.rb:49:in `open'
from /var/lib/gems/1.9.1/gems/bonsai-1.4.9/lib/bonsai/exporter.rb:49:in `block in compress_asset_path'
from /var/lib/gems/1.9.1/gems/bonsai-1.4.9/lib/bonsai/exporter.rb:47:in `each'
from /var/lib/gems/1.9.1/gems/bonsai-1.4.9/lib/bonsai/exporter.rb:47:in `compress_asset_path'
from /var/lib/gems/1.9.1/gems/bonsai-1.4.9/lib/bonsai/exporter.rb:42:in `compress_assets'
from /var/lib/gems/1.9.1/gems/bonsai-1.4.9/lib/bonsai/exporter.rb:23:in `publish!'
from /var/lib/gems/1.9.1/gems/bonsai-1.4.9/bin/bonsai:56:in `block (2 levels) in <top (required)>'
from /usr/lib/ruby/1.9.1/optparse.rb:1391:in `call'
from /usr/lib/ruby/1.9.1/optparse.rb:1391:in `block in parse_in_order'
from /usr/lib/ruby/1.9.1/optparse.rb:1347:in `catch'
from /usr/lib/ruby/1.9.1/optparse.rb:1347:in `parse_in_order'
from /usr/lib/ruby/1.9.1/optparse.rb:1341:in `order!'
from /usr/lib/ruby/1.9.1/optparse.rb:1432:in `permute!'
from /usr/lib/ruby/1.9.1/optparse.rb:1453:in `parse!'
from /var/lib/gems/1.9.1/gems/bonsai-1.4.9/bin/bonsai:80:in `<top (required)>'
from /usr/local/bin/bonsai:23:in `load'
from /usr/local/bin/bonsai:23:in `<main>'
```

**Comment by benschwarz** [comment]
Thanks for the stack trace @gburzynski — I'm guessing that updates downstream in YUI compressor broke this. Reckon you'd be able to fish around for more detail?

**Comment by gburzynski** [comment]
Okay, I managed to fix the problem with just reinstalling gems and installing yui-compressor from repos, then running --repot on sudo rights. Everything works like a charm :+1: 
Thanks for a great project!
